import { PortfolioData } from 'models/Portfolio';

export const PORTFOLIO_DATA: PortfolioData[] = [
  {
    category: 'my-work',
    image: '',
    video: require('assets/video/React full company website.mp4'),
    url: 'https://howardmui-company.netlify.app/',
    gitHubLink: 'https://github.com/HowardMui/HowardMui-Company-ReactProject',
    title: 'My React Company Website',
    content: '',
    tags: ['React', 'Nodejs', 'MongoDb'],
  },
  {
    category: 'my-work',
    image: '',
    video: '',
    url: 'https://howardmui-fetchpexels-project.netlify.app/',
    gitHubLink: 'https://github.com/HowardMui/Howard-fetchAPI-pexels',
    title: 'My Fetch Images Website',
    content: '',
    tags: ['React', 'Nodejs'],
  },
  {
    category: 'appicidea',
    image: '',
    video: null,
    url: null,
    gitHubLink: null,
    title: 'SV Web Application',
    content: '',
    tags: ['React', 'Nodejs'],
  },
  {
    category: 'appicidea',
    image: '',
    video: null,
    url: null,
    gitHubLink: null,
    title: 'SV CMS',
    content: '',
    tags: ['Typescript', 'Reactjs', 'Nodejs'],
  },
  {
    category: 'appicidea',
    image: '',
    video: null,
    url: null,
    gitHubLink: null,
    title: 'Weave-living CMS',
    content: '',
    tags: ['Typescript', 'React', 'Nodejs'],
  },
  {
    category: 'appicidea',
    image: '',
    video: null,
    url: null,
    gitHubLink: null,
    title: 'Fader CMS',
    content: '',
    tags: ['Typescript', 'React', 'Nodejs'],
  },
  {
    category: 'appicidea',
    image: '',
    video: null,
    url: null,
    gitHubLink: null,
    title: 'Man Space Mobile App',
    content: '',
    tags: ['Typescript', 'React-Native', 'Nodejs'],
  },
];
